namespace Scott.Cab.Generation.Common
{
    public static class Templates
    {
        public static readonly string Header = @"/// <auto-generated>
/// This file is auto-generated. All changes will be discarded.
/// Source Generator written by Scott.Cab 2023.
/// See: https://github.com/iamscottcab/unity-source-generators for more info.
/// </auto-generated>";
    }
}
